#!/usr/bin/env bash
#Build the image
docker build -t my-apache-image .
#Run the container
docker run -d -p 8080:80 --name apache-gboso my-a
pache-image
#Check the container is running
docker ps
#Access Apache
curl http://localhost:8080
